name: sample-vite-react
services:
- build_command: yarn build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: false
    repo: digitalocean/sample-vite-react
  name: sample-vite-react